name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      REACT_APP_SECRET_KEY: mock-secret-key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run unit tests
        run: npm run test:ci

      - name: Run end-to-end tests
        env:
          BROWSER: none
        run: npm run e2e
